### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wyuzl** [XPixelGroup/HAT#10]
你好，请问可以提供完整数据集的下载路径 or 制作完整数据集具体方法，谢谢

**Comment by chxy95** [comment]
@wyuzl DF2K下载和处理可以参考[BasicSR](https://github.com/XPixelGroup/BasicSR/blob/master/docs/DatasetPreparation.md#image-super-resolution)。ImageNet直接从官网下载后参考上述链接制作meta_info文件即可。

**Comment by wyuzl** [comment]
感谢您的回答，在论文中，您提到了对input做了数据增强，但我们在代码中没有找到这部分的操作，为了能够保持数据和参数的一致性，所以才询问您是否能够提供完整的制作好的数据集，方便做模型的复现，以及在此工作上的一些改进，谢谢

**Comment by chxy95** [comment]
@wyuzl 数据增强在代码中有体现，具体实现你可以参考源码[paired_image_dataset.py](https://github.com/XPixelGroup/BasicSR/blob/master/basicsr/data/paired_image_dataset.py)。提供的训练option文件里默认是打开数据增强的，不需要额外设置。数据集本身并没有做增强处理，按照上个回复提供的链接制作就行。制作好的DF2K sub-images大约要70G，不方便上传。

**Comment by wyuzl** [comment]
感谢您的回答，还有个疑问，论文中说 “DF2K (DIV2K [31]+Flicker2K [47]) with 3360 images” ，使用了3360张HR，但是800+2650=3450 ？

**Comment by chxy95** [comment]
@wyuzl 检查了一下确实是3450。这里是错算成了2560+800=3360...
