### ISSUE TITLE
问题有点大

### ISSUE THREAD

**Issue by Hanzc989** [XPixelGroup/HAT#100]
已修改

**Comment by Hanzc989** [comment]
代码还没有仔细看, 只是test了

**Comment by chxy95** [comment]
@Hanzc989 方便的话可以直接微信讨论一下wx: Genius07

**Comment by Hanzc989** [comment]
> @Hanzc989 方便的话可以直接微信讨论一下wx: Genius07，或者留一下联系方式~

加你了, 通过一下, 我叫 韩.......xx
