### ISSUE TITLE
各位大佬好，这个放大模型是SwinIR架构的吗？能适配auto1111的Stable diffusion来做图像放大吗？

### ISSUE THREAD

**Issue by Erwin11** [XPixelGroup/HAT#102]
我不是很懂，这个模型是SwinIR架构的吗？ 
我放到auto1111的Stable diffusion webui /model/SwinIR 模型目录下面，貌似无法读取。

看了下它的实现是目前只能读
[03_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth](https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth)
这个模型是是吗？
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/SwinIR/swinir_model_arch.py

有没有可能让webui 使用这个目前最强的放大算法呢？

**Comment by chxy95** [comment]
@Erwin11 看了下webui目前并不支持使用HAT模型。可以尝试给他们去提一下需求看看~

**Comment by Erwin11** [comment]
我放错目录了， 应该放在“stable-diffusion-webui/models/ESRGAN” 目录下， 可以识别出模型，但是无法使用，应该是webui不支持。

**Comment by Erwin11** [comment]
补充下webui 的不支持提示：KeyError: 'trunk_conv.weight'

**Comment by Erwin11** [comment]
放在“stable-diffusion-webui/models/SwinIR” 目录下是对的，Webui 现在不支持，报错如下：

RuntimeError: Error(s) in loading state_dict for SwinIR: Missing key(s) in state_dict: "layers.0.residual_group.blocks.0.attn.relative_position_index", "layers.0.residual_group.blocks.1.attn_mask", "layers.0.residual_group.blocks.1.attn.relative_position_index", "layers.0.residual_group.blocks.2.attn.relative_position_index", "layers.0.residual_group.blocks.3.attn_mask", "layers.0.residual_group.blocks.3.attn.relative_position_index", "layers.0.residual_group.blocks.4.attn.relative_position_index", "layers.0.residual_group.blocks.5.attn_mask", "layers.0.residual_group.blocks.5.attn.relative_position_index", "layers.0.conv.0.weight", "layers.0.conv.0.bias", "layers.0.conv.2.weight", "layers.0.conv.2.bias", "layers.0.conv.4.weight", "layers.0.conv.4.bias", "layers.1.residual_group.blocks.0.attn.relative_position_index", "layers.1.residual_group.blocks.1.attn_mask", "layers.1.residual_group.blocks.1.attn.relative_position_index", "layers.1.residual_group.blocks.2.attn.relative_position_index", "layers.1.residual_group.blocks.3.attn_mask", "layers.1.residual_group.blocks.3.attn.relative_position_index", "layers.1.residual_group.blocks.4.attn.relative_position_index", "layers.1.residual_group.blocks.5.attn_mask", "layers.1.residual_group.blocks.5.attn.relative_position_index", "layers.1.conv.0.weight", "layers.1.conv.0.bias", "layers.1.conv.2.weight", "layers.1.conv.2.bias", "layers.1.conv.4.weight", "layers.1.conv.4.bias", "layers.2.residual_group.blocks.0.attn.relative_position_index", "layers.2.residual_group.blocks.1.attn_mask", "layers.2.residual_group.blocks.1.attn.relative_position_index", "layers.2.residual_group.blocks.2.attn.relative_position_index", "layers.2.residual_group.blocks.3.attn_mask", "layers.2.residual_group.blocks.3.attn.relative_position_index", "layers.2.residual_group.blocks.4.attn.relative_position_index", "layers.2.residual_group.blocks.5.attn_mask", "layers.2.residual_group.blocks.5.attn.relative_position_index", "layers.2.conv.0.weight", "layers.2.conv.0.bias", "layers.2.conv.2.weight", "layers.2.conv.2.bias", "layers.2.conv.4.weight", "layers.2.conv.4.bias", "layers.3.residual_group.blocks.0.attn.relative_position_index", "layers.3.residual_group.blocks.1.attn_mask", "layers.3.residual_group.blocks.1.attn.relative_position_index", "layers.3.residual_group.blocks.2.attn.relative_position_index", "layers.3.residual_group.blocks.3.attn_mask", "layers.3.residual_group.blocks.3.attn.relative_position_index", "layers.3.residual_group.blocks.4.attn.relative_position_index", "layers.3.residual_group.blocks.5.attn_mask", "layers.3.residual_group.blocks.5.attn.relative_position_index", "layers.3.conv.0.weight", "layers.3.conv.0.bias", "layers.3.conv.2.weight", "layers.3.conv.2.bias", "layers.3.conv.4.weight", "layers.3.conv.4.bias", "layers.4.residual_group.blocks.0.attn.relative_position_index", "layers.4.residual_group.blocks.1.attn_mask", "layers.4.residual_group.blocks.1.attn.relative_position_index", "layers.4.residual_group.blocks.2.attn.relative_position_index", "layers.4.residual_group.blocks.3.attn_mask", "layers.4.residual_group.blocks.3.attn.relative_position_index", "layers.4.residual_group.blocks.4.attn.relative_position_index", "layers.4.residual_group.blocks.5.attn_mask", "layers.4.residual_group.blocks.5.attn.relative_position_index", "layers.4.conv.0.weight", "layers.4.conv.0.bias", "layers.4.conv.2.weight", "layers.4.conv.2.bias", "layers.4.conv.4.weight", "layers.4.conv.4.bias", "layers.5.residual_group.blocks.0.attn.relative_position_index", "layers.5.residual_group.blocks.1.attn_mask", "layers.5.residual_group.blocks.1.attn.relative_position_index", "layers.5.residual_group.blocks.2.attn.relative_position_index", "layers.5.residual_group.blocks.3.attn_mask", "layers.5.residual_group.blocks.3.attn.relative_position_index", "layers.5.residual_group.blocks.4.attn.relative_position_index", "layers.5.residual_group.blocks.5.attn_mask", "layers.5.residual_group.blocks.5.attn.relative_position_index", "layers.5.conv.0.weight", "layers.5.conv.0.bias", "layers.5.conv.2.weight", "layers.5.conv.2.bias", "layers.5.conv.4.weight", "layers.5.conv.4.bias", "layers.6.residual_group.blocks.0.norm1.weight", "layers.6.residual_group.blocks.0.norm1.bias", "layers.6.residual_group.blocks.0.attn.relative_position_bias_table", "layers.6.residual_group.blocks.0.attn.relative_position_index", "layers.6.residual_group.blocks.0.attn.qkv.weight", "layers.6.residual_group.blocks.0.attn.qkv.bias", "layers.6.residual_group.blocks.0.attn.proj.weight", "layers.6.residual_group.blocks.0.attn.proj.bias", "layers.6.residual_group.blocks.0.norm2.weight", "layers.6.residual_group.blocks.0.norm2.bias", "layers.6.residual_group.blocks.0.mlp.fc1.weight", "layers.6.residual_group.blocks.0.mlp.fc1.bias", "layers.6.residual_group.blocks.0.mlp.fc2.weight", "layers.6.residual_group.blocks.0.mlp.fc2.bias", "layers.6.residual_group.blocks.1.attn_mask", "layers.6.residual_group.blocks.1.norm1.weight", "layers.6.residual_group.blocks.1.norm1.bias", "layers.6.residual_group.blocks.1.attn.relative_position_bias_table", "layers.6.residual_group.blocks.1.attn.relative_position_index", "layers.6.residual_group.blocks.1.attn.qkv.weight", "layers.6.residual_group.blocks.1.attn.qkv.bias", "layers.6.residual_group.blocks.1.attn.proj.weight", "layers.6.residual_group.blocks.1.attn.proj.bias", "layers.6.residual_group.blocks.1.norm2.weight", "layers.6.residual_group.blocks.1.norm2.bias", "layers.6.residual_group.blocks.1.mlp.fc1.weight", "layers.6.residual_group.blocks.1.mlp.fc1.bias", "layers.6.residual_group.blocks.1.mlp.fc2.weight", "layers.6.residual_group.blocks.1.mlp.fc2.bias", "layers.6.residual_group.blocks.2.norm1.weight", "layers.6.residual_group.blocks.2.norm1.bias", "layers.6.residual_group.blocks.2.attn.relative_position_bias_table", "layers.6.residual_group.blocks.2.attn.relative_position_index", "layers.6.residual_group.blocks.2.attn.qkv.weight", "layers.7.residual_group.blocks.2.norm2.weight", "layers.7.residual_group.blocks.2.norm2.bias", "layers.7.residual_group.blocks.2.mlp.fc1.weight", "layers.7.residual_group.blocks.2.mlp.fc1.bias", "layers.7.residual_group.blocks.2.mlp.fc2.weight", "layers.7.residual_group.blocks.2.mlp.fc2.bias", "layers.7.residual_group.blocks.3.attn_mask", "layers.7.residual_group.blocks.3.norm1.weight", "layers.7.residual_group.blocks.3.norm1.bias", "layers.7.residual_group.blocks.3.attn.relative_position_bias_table", "layers.7.residual_group.blocks.3.attn.relative_position_index", "layers.7.residual_group.blocks.3.attn.qkv.weight", "layers.7.residual_group.blocks.3.attn.qkv.bias", "layers.7.residual_group.blocks.3.attn.proj.weight", cks.3.conv_block.cab.3.attention.1.weight", "layers.3.residual_group.blocks.3.conv_block.cab.3.attention.1.bias", "layers.3.residual_group.blocks.3.conv_block.cab.3.attention.3.weight", ······
ize([961, 6]) from checkpoint, the shape in current model is torch.Size([225, 8]). size mismatch for layers.0.residual_group.blocks.3.attn.qkv.weight: copying a param with shape torch.Size([540, 180]) from checkpoint, the shape in current model is torch.Size([720, 240]). size mismatch for layers.0.residual_group.blocks.3.attn.qkv.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([720]). size mismatch for ape in current model is torch.Size([240, 480]). size mismatch for layers.5.residual_group.blocks.5.mlp.fc2.bias: copying a param with shape torch.Size([180]) from checkpoint, the shape in current model is torch.Size([240]). size mismatch for norm.weight: copying a param with shape torch.Size([180]) from checkpoint, the shape in current model is torch.Size([240]). size mismatch for norm.bias: copying a param with shape torch.Size([180]) from checkpoint, the shape in current model is torch.Size([240]). size mismatch for conv_before_upsample.0.weight: copying a param with shape torch.Size([64, 180, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 240, 3, 3]).
Time taken: 0.86sTorch active/reserved: 53/68 MiB, Sys VRAM: 2157/6144 MiB (35.11%)

**Comment by chxy95** [comment]
@Erwin11 可以去提一下需求，或者自行更改它们的repo添加HAT model。参考SwinIR添加或修改对应的model和config为HAT就行。

**Comment by Erwin11** [comment]
@chxy95   感谢您百忙之中还及时回复！  auto1111 那边我已经提了 issue 建议，还没得到回复。

嗯。。 webui 那边我也看了作者@C43H66N12O12S2 的技术实现。 
（ 内置SwinIR 和SwinIR v2 是同一人[@C43H66N12O12S2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/725) )

参考SwinIR v2 的[添加](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092/files)，

作者@C43H66N12O12S2 是改了[swinir_model.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092/files#diff-ab63bbc1fb27e928d39a4ac304dcb09975d2948b7e3bd6fab1e76fac36f8a6f8) (调度模块？) 和 新增了 [swinir_model_arch_v2.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092/files#diff-2b0c9221fb1db46cbd3869687d0645f3681d303c6f3ea797de0ed113ca5f54a6) (架构文件？)。

swinir_model.py 进行修改，新增了SwinIR v2 的模块的net参数，相关参数如下：
 model = net(
                upscale=scale,
                in_chans=3,
                img_size=64,
                window_size=8,
                img_range=1.0,
                depths=[6, 6, 6, 6, 6, 6, 6, 6, 6],
                embed_dim=240,
                num_heads=[8, 8, 8, 8, 8, 8, 8, 8, 8],
                mlp_ratio=2,
                upsampler="nearest+conv",
                resi_connection="3conv",

关于这个参数在 HAT 模型是多少我不清楚。

新增架构的文件[swinir_model_arch_v2.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092/files#diff-2b0c9221fb1db46cbd3869687d0645f3681d303c6f3ea797de0ed113ca5f54a6)
是在原内置的 [swinir_model_arch.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/SwinIR/swinir_model_arch.py) 基础上改的，HAT 是新架构， 可能要加个这个文件进去。 我是外行，只能理解到这里了。
期待他们的更新吧

**Comment by chxy95** [comment]
@Erwin11 我没详细看，但是如果要自己尝试的话，感觉可能也不复杂。原理上应该把这个repo里的网络架构代码[hat_arch.py](https://github.com/XPixelGroup/HAT/blob/main/hat/archs/hat_arch.py)添加或改写到那边的模型文件里，即[swinir_model_arch_v2.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092/files#diff-2b0c9221fb1db46cbd3869687d0645f3681d303c6f3ea797de0ed113ca5f54a6)，然后相关参数配置参考你要inference的test option文件如[HAT_SRx4_ImageNet-LR.yml](https://github.com/XPixelGroup/HAT/blob/8bb08675a736e2c1697e859d2645d893d11a05c4/options/test/HAT_SRx4_ImageNet-LR.yml#L19) 就行。

**Comment by Erwin11** [comment]
@chxy95  comfyUI 可以使用！
个人体会，动漫部分和R-ESRGAN差异不是很明显，R-ESRGAN较容易出现放大后的涂抹光斑这是一个问题。
真人部分，背景理解HAT最好，特别对于马路这种规则纹理，R-ESRGAN已经是开始乱造了。

不过时间开销 R-ESRGAN_Anime_6B 还是快，快30%左右， 举个例子 R-ESRGAN_Anime_6B 跑408s, HAT要跑618s


![HAT最好 HAT sharper添加了耳环 他们的马路都很好，ultra sharp和R-ESRGAN都在乱画马路](https://github.com/XPixelGroup/HAT/assets/6300501/44582b3e-1abc-407e-a81c-a4d67478950c)

![遇到主体和背景相似的或者分离的， 背景R-ESRGAN会乱造 马路开始乱造了  HAT 2个都有细节](https://github.com/XPixelGroup/HAT/assets/6300501/f0077b9a-f025-426b-91c6-5279d99e87d5)

**Comment by Erwin11** [comment]
### R-ESRGAN的眼睛最好，但是手部有蓝斑
![R-ESRGAN的眼睛最好，但是手部有蓝斑](https://github.com/XPixelGroup/HAT/assets/6300501/b7a142f9-1c25-4a57-8182-4e9fd544b2f5)

### R-ESRGAN帽子丢失了些细节，Ultrasharp和HAT默认都还好，HATsharper和R-ESRGAN过度锐化了
![R-ESRGAN帽子丢失了些细节，Ultrasharp和HAT默认都还好，HATsharper和R-ESRGAN过度锐化了](https://github.com/XPixelGroup/HAT/assets/6300501/1111cdf7-f227-4436-b7d2-69853d55572b)

**Comment by Erwin11** [comment]
### 背景网格HAT会出现（虽然不怎样），R-ESRGAN直接涂抹
![背景网格HAT会出现（虽然不怎样），R-ESRGAN直接涂抹](https://github.com/XPixelGroup/HAT/assets/6300501/238c69d7-8080-43a4-9627-dc7fbfc792ef)

### 书架部分R-ESRGAN识别成光斑 其他和HAT都差不多 没有明显差异
![书架部分R-ESRGAN识别成光斑 其他和HAT都差不多 没有明显差异](https://github.com/XPixelGroup/HAT/assets/6300501/8ccbafd7-a3cd-49d2-9175-045305d0b91f)
