### ISSUE TITLE
Replicate demo not working

### ISSUE THREAD

**Issue by JoelKronander** [XPixelGroup/HAT#12]
It appears the replicate demo throws an error currently?

**Comment by chxy95** [comment]
@JoelKronander Could you be more specific about the problem you're meeting? I just ran this demo on the website and no errors came up.

**Comment by JoelKronander** [comment]
@chxy95 Yes, sorry. Here is an example
![Screen Shot 2022-08-29 at 1 21 40 PM](https://user-images.githubusercontent.com/18355572/187291267-eccaa866-3029-40d5-8079-2bb7d78c6db6.png)

**Comment by chxy95** [comment]
@JoelKronander This error occurs because the input image resolution is large and there is not enough CUDA memory to run the model. You may change some other images with relatively small resolution or run the model with the image in your own devices with more CUDA memory.

**Comment by JoelKronander** [comment]
@chxy95 Ah ok, could the model be moved to A100 card? seems silly not to be able to upload a 512x512 image for upsampling?

**Comment by chxy95** [comment]
This problem has been solved.

**Comment by xyz53** [comment]
Hi @chxy95 , it seems the predictions are back on the T4, which is causing the error mentioned above. Is there any workaround for this?

**Comment by chxy95** [comment]
@xyz53 Intending to update but currently no specific timeline. Try using the code or [chaiNNer](https://github.com/chaiNNer-org/chaiNNer).
