### ISSUE TITLE
Question about "overlap_ratio"

### ISSUE THREAD

**Issue by blackcow** [XPixelGroup/HAT#15]
As state in the paper, the window_size M_0 of OCAB = (1 + 2*overlap_ratio) * M 

However, the code implementation appears to be in conflict.

https://github.com/XPixelGroup/HAT/blob/09e797326afd27e690a3cffac92c7de13bfa069d/hat/archs/hat_arch.py#L373

**Comment by chxy95** [comment]
Hi @blackcow, thanks for your attention. I have just checked the paper and the codes, and this is indeed a small mistake in the presentation of the paper. Fortunately,  **γ** as a hyperparameter, it does not affect the essential experimental conclusions. I will correct the describtion of this operation in the paper and release an updated version asap.
