### ISSUE TITLE
Does HAT have tile mode?

### ISSUE THREAD

**Issue by ichsan2895** [XPixelGroup/HAT#16]
Hello, congratulation for getting highest score in "paperwithcode" benchmark summary. But, I curious with HAT, so I installed it.

I inference an image

`!python hat/test.py -opt options/test/HAT_SRx4_ImageNet-LR.yml`

But, it was errror because CUDA out of memory. I'm sorry because my VRAM only 2 GB. Yeah, I will try with google colab, but it has limited time and GPU quota.

Can HAT has a feature like tiling the image? for example
`!python hat/test.py -opt options/test/HAT_SRx4_ImageNet-LR.yml --tile 256`

**Comment by chxy95** [comment]
Hi @ichsan2895, I haven't integrated tile mode into this repo. I will add this function soon. Before that, you can try our method in the [replicate](https://replicate.com/xpixelgroup/hat).

**Comment by chxy95** [comment]
The tile mode is provided for limited GPU memory when testing. The setting can be referred to https://github.com/XPixelGroup/HAT/blob/39eeb5c28741b05ed2f23f13ff9131efe7539fde/options/test/HAT_tile_example.yml#L7-L9

**Comment by ziippy** [comment]
Something wrong.

I tested my image for get a psnr result.

I try test without tile ---> psnr 25.6524
I try test with tile -------> psnr 25.5012

something different the value of the psnr result.

Did you check the both results are same?

**Comment by ichsan2895** [comment]
> The tile mode is provided for limited GPU memory when testing. The setting can be referred to
> 
> https://github.com/XPixelGroup/HAT/blob/1d157411076a2d485b13c711a6a521abf62758b0/options/test/HAT_tile_example.yml#L7-L9

wow thanks for that implementation, I will test it out later

**Comment by dreamflasher** [comment]
Please add the tiling settings to replicate. So far I wasn't able to run hat on any image that I cared about, due to OOM.
Btw. is HAT or HAT-L running on replicate? Would be nice to add that to the description.

**Comment by ichsan2895** [comment]
Ups sorry, I forget to close it.
