### ISSUE TITLE
Can you modify for train_1, train_2 ... like val_1, val_2 ...?

### ISSUE THREAD

**Issue by ziippy** [XPixelGroup/HAT#20]
I want to train with separated folders like train_1, train_2.

I checked the .yaml support multiple validation directory like val_x.
but, train_x is not supported. 
Is there any plan for supporting that?

my GT is divided separated with each domain. (load, bird, car, ... and so on)
So, If you can. please do that.

**Comment by chxy95** [comment]
You can put multiple folders in the same directory and use this directory as the dataset path. Then 1) you can rewrite a data loader file by setting the `recursive` to True for the `scandir` function as `scandir(path, recursive=True, full_path=True)` https://github.com/XPixelGroup/HAT/blob/4a77c403a0982fbb141453680c4c07569f91447b/hat/data/imagenet_paired_dataset.py#L35
2) or you can generate a meta info file by using [generate_meta_info.py](https://github.com/XPixelGroup/BasicSR/blob/master/scripts/data_preparation/generate_meta_info.py) to scan the data.
