### ISSUE TITLE
Questions related to pre-trained dataset ImageNet

### ISSUE THREAD

**Issue by GoPikachue** [XPixelGroup/HAT#23]
Thank you for your outstanding work! I have some questions about the ImageNet dataset that I would like to ask you.
   1. I find it a bit confusing that in the pre-training yml file there are only GT files about ImageNet and no LR files.
   2. There are some images with small size (e.g. less than 256x256) inside the ImageNet dataset, how do you handle for these images?
   3. By the way, can you give me an overview of the ImageNet dataset preparation?
   Looking forward to your reply!

**Comment by chxy95** [comment]
@GoPikachue Reading the data loader file to solve the first two questions. For dataset preparation, you only need to generate the meta info file according to your own data organization.

**Comment by GoPikachue** [comment]
OK, I haven't read the relevant documents carefully yet, I will go through them first.
