### ISSUE TITLE
Training Error. Could you provide some guidance on how to fix this error?

### ISSUE THREAD

**Issue by yazidoudou18** [XPixelGroup/HAT#25]
FileNotFoundError: [Errno 2] No such file or directory: '/qfs/projects/mage/watk681/DIV2K_train_HR/DIV2K_train_HR/002116_s044.png'
 

However, DIV2K/DIV2K_train_HR/ uses 0001.png, 0002.png, ..., 0800.png. 
Any guidance on how to generate the compatible meta_info_DF2Ksub_GT.txt to work with DIV2K/DIV2K_train_HR/ uses 0001.png, 0002.png, ..., 0800.png.?

**Comment by chxy95** [comment]
Follow the [Preparation Steps](https://github.com/XPixelGroup/BasicSR/blob/master/docs/DatasetPreparation.md#div2k).
