### ISSUE TITLE
Training time issues

### ISSUE THREAD

**Issue by GoPikachue** [XPixelGroup/HAT#26]
I would like to ask you how long did it take you to train x2SR from scratch using DF2K?

**Comment by chxy95** [comment]
about 2~3 days

**Comment by GoPikachue** [comment]
Thank you for your reply, I have one more question for you. I only have 4 3090 GPUs. how should I set my training strategy if I want to achieve the same training results?

**Comment by chxy95** [comment]
You may try to set small batch size but train more iterations for the highest possible performance.

**Comment by GoPikachue** [comment]
Ok, thank you for your reply.
