### ISSUE TITLE
Can you tell me how to preprocess images in HAT?

### ISSUE THREAD

**Issue by saeu5407** [XPixelGroup/HAT#27]
Thank you for sharing your code.

It appears to use BGR images during preprocessing.

Can I know the process of preprocessing other than this? (Example. Divide by 255)

**Comment by chxy95** [comment]
@saeu5407 Check [paired_image_dataset.py](https://github.com/XPixelGroup/BasicSR/blob/v1.3.4.9/basicsr/data/paired_image_dataset.py) for details.

**Comment by saeu5407** [comment]
thank you for your reply.
