### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by dillfrescott** [XPixelGroup/HAT#31]
Every image I've tried to upscale with HAT just seems to stretch the image to a larger, even more blurrier size. I've tried all sorts of sizes ranging from 64x64 to 1024x1024. It seems to just click and drag the image larger for me without actually enhancing anything.

Am I doing something wrong? I'd love to be able to use this project but right now its very confusing to me. :/

**Comment by chxy95** [comment]
@dillfrescott Maybe your test samples are too hard for the model. You can try the GAN-based HAT model. https://drive.google.com/file/d/1Ma12vCWT27P9M99-s2RXnynKN-OQsBrv/view?usp=share_link

**Comment by dillfrescott** [comment]
Ooooo okay! I will try that! Thank you!

**Comment by dillfrescott** [comment]
Ok this seems to work much better! Thank you!

**Comment by shreykshah** [comment]
What config was used for the GAN-based HAT model?

**Comment by dillfrescott** [comment]
I just used chaiNNer: `https://github.com/chaiNNer-org/chaiNNer`

Using it you don't need a config. Its somehow handled automatically
