### ISSUE TITLE
ImageNet pre-trained HAT-L models without any fine-tuning.

### ISSUE THREAD

**Issue by USTC-JialunPeng** [XPixelGroup/HAT#35]
Hi, thank you for your great work! I want to test the performance of ImageNet pre-trained HAT-L models without fine-tuning on DF2K. When pre-training HAT-L on the ImageNet dataset, the training time is long (about 13 days using 8 V100 GPUs). Could you please release those ImageNet pre-trained HAT-L models without any fine-tuning? Thanks for replying!

**Comment by chxy95** [comment]
@USTC-JialunPeng I'm not sure if the files are still preserved. I will check it these two days.

**Comment by USTC-JialunPeng** [comment]
@chxy95 Thanks for your help！

**Comment by chxy95** [comment]
@USTC-JialunPeng [BaiduYun](https://pan.baidu.com/s/1hnQtq7RWKJA_qnF1ttO5YQ) access code: vacr

**Comment by USTC-JialunPeng** [comment]
@chxy95 Thank you！
