### ISSUE TITLE
How to run inference?

### ISSUE THREAD

**Issue by junghyun-avikus** [XPixelGroup/HAT#41]
I am trying to inference some of my images, but readme doesn't really tell how to run inference other than test.
Could you briefly go over how to run inference?

Also, it seems like BasicSR must be integrated into this repository. Do I just copy and paste all the files from the BasicSR repository into this repository?

**Comment by dillfrescott** [comment]
Use ChaiNNer: https://github.com/chaiNNer-org/chaiNNer

It supports the HAT models and you just wire it up and it works!

Hope that helps!
