### ISSUE TITLE
Overlapping ratio difference between paper and implementation

### ISSUE THREAD

**Issue by Gwenn-LR** [XPixelGroup/HAT#44]
Hi! 

I'm currently studying your implementation and your publication and I was wondering : Is there an explanation for your Equ. 9 and precisely for the factor of 2 to the overlapping ratio ?

I'm just asking since in your implementation at hat_arch.py it seems to me that you only use  (1 + $\gamma$) $\times$ M as formula (lines 373 and 899) and it might change your interpretation of this hyperparameter in your publication (small ones), but I also might have missed something and be wrong.

Otherwise, thanks for your amazing work!

**Comment by chxy95** [comment]
@Gwenn-LR #15 This is indeed our mistake in the presentation of the paper. The corrected version will be released this month.
