### ISSUE TITLE
Questions about the structure of the model

### ISSUE THREAD

**Issue by Zency-Sun** [XPixelGroup/HAT#53]
Hello author, thank you for your great work. I would like you a question about the model.
**In your HAT model architecture, the HAB includes CAB, which I understand is derived from RCAB in RCAN, I would like to know why you did not use RCAB but CAB when designing the network, and have you done any ablation studies to explore how RCAB/CAB affects the model?**
I would be grateful if you would replay！

**Comment by chxy95** [comment]
A residual connection already exists in HAB.
