### ISSUE TITLE
Fine-tuning the model will generate weird noises in the super-resolved images

### ISSUE THREAD

**Issue by oubotong** [XPixelGroup/HAT#58]
Thanks for this excellent work! 

I have a question regarding fine-tuning the model `HAT-L_SRx4_ImageNet-pretrain.pth` . 
As I am training on my own dataset and when the iteration increases, the super-resolved images will contain some weird noises. Here are  an example when testing:

30000 iterations (x4 result):
![buildings00_HAT-L_SRx4_ImageNet-pretrain](https://user-images.githubusercontent.com/26356127/229327727-04b87d0c-6e30-49a8-ad82-e8cd23ee11eb.png)

40000 iterations (x4 result):
![buildings00_HAT-L_SRx4_ImageNet-pretrain](https://user-images.githubusercontent.com/26356127/229327768-55ed7384-09e3-47d9-bd26-ad59682f583c.png)

200000 iterations (x4 result):
![buildings00_HAT-L_SRx4_ImageNet-pretrain](https://user-images.githubusercontent.com/26356127/229327844-6eae5395-a74a-45cf-a949-f66b0aa56763.png)

Do you have any idea why this would happen?
Thanks!

**Comment by chxy95** [comment]
@oubotong I guess it is because the scale of your training dataset is too small leading to serious overfitting with weird artifacts. From my experience, finetuning for HAT-L only needs very little iterations (within 20k).
