### ISSUE TITLE
About the model size

### ISSUE THREAD

**Issue by Alidaling** [XPixelGroup/HAT#71]
Why does the Real_HAT_GAN_SRx4.pth model, which has the same configuration parameters as the HAT_SRx4.pth model, appear to be larger in size (163M) compared to the HAT_SRx4.pth model (82M)?

**Comment by chxy95** [comment]
Real_HAT_GAN_SRx4.pth stores a dict of params without using ema decay. It affacts nothing. I just do not delete it.
