### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/DF2K/DF2K_bicx2_sub/2761_s043.png'

### ISSUE THREAD

**Issue by Youxuanc** [XPixelGroup/HAT#78]
跟題目所述一樣，使用python hat/train.py -opt options/train/train_HAT_SRx2_from_scratch.yml作訓練。Data 使用BasicSR 中的Dataset Preparation 去作Crop to sub-images，但做完後形成的sub-image，在/DIV2K_train_LR_bicubic/X2_sub 中沒有2761_s043.png此張圖片。

**Comment by sunsunshark** [comment]
I meet the same trouble. How do you solve this question ?
