### ISSUE TITLE
ImportError: cannot import name 'rgb2ycbcr'

### ISSUE THREAD

**Issue by yumulinfeng1** [XPixelGroup/HAT#8]
运行
`python hat/test.py -opt options/test/HAT_SRx4_ImageNet-pretrain.yml`
报错如上图

**Comment by chxy95** [comment]
@yumulinfeng1 What is the version of basicsr used? Is it `1.3.4.9`? The latest version of basicsr change the location of the function `rgb2ycbcr`.
