### ISSUE TITLE
Can I ask if the REAL HAT 2X will be available use here?

### ISSUE THREAD

**Issue by sanbuphy** [XPixelGroup/HAT#82]
Hello! I have found that the HAT's performance is excellent, especially the real hat. However, I noticed that only the 4x version is available in the Model Zoo. Could you please let me know when the 2x version will be available? Thank you very much!

**Comment by chxy95** [comment]
@sanbuphy hi, x2 model has not trained. I will release the training config this month.

**Comment by sanbuphy** [comment]
> @sanbuphy hi, x2 model has not trained. I will release the training config this month.

Thank you very much ! I think the real model is very cool.  I hope to have pretrained models. I am currently working on exporting your models for deployment, such as ONNX. Thank you for your efforts.
