### ISSUE TITLE
How can i reduce the GPU memory usage

### ISSUE THREAD

**Issue by sanbuphy** [XPixelGroup/HAT#83]
Hello, thank you very much for your algorithm, I find it very useful. However, I currently feel that it occupies a large amount of memory. 

Is there any method to reduce memory usage without significantly affecting the final result? Thank you very much.

**Comment by chxy95** [comment]
Reduce the batch size and training for more iterations

**Comment by sanbuphy** [comment]
> Reduce the batch size and train for more iterations.

Thank you very much
