### ISSUE TITLE
我出现了个报错No object named 'HATModel' found in 'model' registry!" 

### ISSUE THREAD

**Issue by Yuziyi1117** [XPixelGroup/HAT#92]
请问一下 我运行过程中有这个报错，debug的时候发现basicsr/utils/registry.py 中registry._obj_map 里面没有HATModel 请问这个怎么解决呢？ 运行了Python setup,py develop还是不行
![IMG_export_20230831_171204596](https://github.com/XPixelGroup/HAT/assets/15991422/44507759-98b1-4ada-a2fa-941ee5658441)

**Comment by chxy95** [comment]
#28
