### ISSUE TITLE
Very poor reconstruction and strange patterns in Real_HAT_GAN_SRx4_sharper.pth

### ISSUE THREAD

**Issue by kongyuzhuo** [XPixelGroup/HAT#94]
Hi,

Firstly I'm very appreciate this work in SR. But when I used '**Real_HAT_GAN_SRx4_sharper.pth**' to test my own image I found some strange  patterns and mosaics. My comment is '**python hat/test.py -opt options/test/HAT_GAN_Real_SRx4.yml**'. I don't know why I met this question.... Could you help me to desolve this?

![image](https://github.com/XPixelGroup/HAT/assets/101630956/64f35b3f-4b29-41fb-9145-71c8e1f9c3b5)

Best,

**Comment by chxy95** [comment]
@kongyuzhuo look weird... Have you tried other data? Is it just this image or does this happen to all the images you tested?

**Comment by kongyuzhuo** [comment]
> @kongyuzhuo look weird... Have you tried other data? Is it just this image or does this happen to all the images you tested?
Hi, chxy95, I have solved this problem when I switched torch 1.8.1 to torch 1.11.0, and the reconstruction seems normal. Thanks for your help :)
![image](https://github.com/XPixelGroup/HAT/assets/101630956/cf573a44-ebfa-4010-98f8-ab6fcebd0e0c)
